# Generated by Django 4.0.6 on 2022-08-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrunners_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tightening',
            name='model',
        ),
    ]
