# Generated by Django 4.0.6 on 2022-08-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrunners_data', '0003_alter_vehicle_vin_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tightening',
            old_name='vin_number',
            new_name='vin',
        ),
    ]
